#!/bin/sh
set -e
echo "Activating feature 'ros'"

ROS_DISTRO_OPT=${ROSDISTRO:-auto}
WORKSPACE_SETUP=${WORKSPACESETUPPATH:-}
TARGET_USER="${TARGETUSER:-${_REMOTE_USER:-root}}"

if [ "$TARGET_USER" = "root" ]; then
    USER_HOME="/root"
else
    USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)
    if [ -z "$USER_HOME" ]; then
        echo "Error: could not determine home directory for user '$TARGET_USER'" >&2
        exit 1
    fi
fi

echo "ROS feature: distro='$ROS_DISTRO_OPT', user='$TARGET_USER', home='$USER_HOME'"

# Detect or validate the ROS distro
if [ "$ROS_DISTRO_OPT" = "auto" ]; then
    if [ ! -d /opt/ros ] || [ -z "$(ls -A /opt/ros 2>/dev/null)" ]; then
        echo "No ROS installation found at /opt/ros — skipping ROS environment setup." >&2
        exit 0
    fi
    # Pick the lexicographically latest distro (e.g. jazzy > humble > galactic)
    DISTRO=$(ls /opt/ros | sort -V | tail -1)
    echo "Auto-detected ROS distro: $DISTRO"
else
    DISTRO="$ROS_DISTRO_OPT"
    if [ ! -d "/opt/ros/$DISTRO" ]; then
        echo "Warning: /opt/ros/$DISTRO does not exist. The source lines will be written" >&2
        echo "         but will be no-ops until ROS $DISTRO is installed in the container." >&2
    fi
fi

# Write ~/.bashrc_ros with conditional sourcing so it is safe on non-ROS containers
ROS_RC="$USER_HOME/.bashrc_ros"
cat > "$ROS_RC" << EOF
# ROS environment setup (generated by devcontainer feature)
if [ -f "/opt/ros/${DISTRO}/setup.bash" ]; then
    . "/opt/ros/${DISTRO}/setup.bash"
fi
if [ -n "\$ZSH_VERSION" ] && [ -f "/opt/ros/${DISTRO}/setup.zsh" ]; then
    . "/opt/ros/${DISTRO}/setup.zsh"
fi
EOF

# Optionally source a local workspace overlay
if [ -n "$WORKSPACE_SETUP" ]; then
    cat >> "$ROS_RC" << EOF

# Workspace overlay
if [ -f "${WORKSPACE_SETUP}" ]; then
    . "${WORKSPACE_SETUP}"
fi
EOF
fi

echo "Wrote ROS environment to $ROS_RC"

# Append an idempotent source line to .bashrc and .zshrc
SOURCE_LINE='[ -f "$HOME/.bashrc_ros" ] && . "$HOME/.bashrc_ros"'
for rc_name in .bashrc .zshrc; do
    base_rc="$USER_HOME/$rc_name"
    if [ -f "$base_rc" ]; then
        grep -qxF "$SOURCE_LINE" "$base_rc" || echo "$SOURCE_LINE" >> "$base_rc"
        echo "Wired .bashrc_ros into $base_rc"
    fi
done

# Fix ownership for non-root
if [ "$TARGET_USER" != "root" ]; then
    chown "$TARGET_USER:$TARGET_USER" "$ROS_RC"
fi

echo "ROS environment setup complete (distro: $DISTRO)."
